Test key files individually

diff --git a/.github/workflows/check-encrypt-key.yaml b/.github/workflows/check-encrypt-key.yaml
--- a/.github/workflows/check-encrypt-key.yaml
+++ b/.github/workflows/check-encrypt-key.yaml
@@ -13,21 +13,26 @@ jobs:
 
       - name: Check encryption keys
         run: |
-          tmpkeys=$(mktemp)
-          OPTS="--no-default-keyring --keyring $tmpkeys"
-
-          gpg $OPTS --import gpg/*
-
-          recipients=""
+          keyfiles=$(ls gpg/*)
           faillist=""
-          for recipient in $(gpg $OPTS --list-keys --with-colons | grep uid | cut -d: -f 10 | sed -r 's/^.*<(.*)>$/\1/'); do
-              tmpfile=$(mktemp)
-              # Test encrypting a temp file to make sure these are encrypt keys, and not just signing keys
-              gpg $OPTS -e --trust-model always -r "$recipient" "$tmpfile" 2>/dev/null \
-                  || faillist="$faillist\n$recipient"
-              rm $tmpfile
+
+          for key in $keyfiles; do
+            tmpkeys=$(mktemp)
+            tmpfile=$(mktemp)
+
+            OPTS="--no-default-keyring --keyring $tmpkeys"
+            gpg $OPTS --quiet --import $key
+
+            recipient=$(gpg $OPTS --list-keys --with-colons | grep uid | cut -d: -f 10 | sed -r 's/^.*<(.*)>$/\1/'| sort -u)
+
+            echo "Checking $key"
+            gpg $OPTS -e --trust-model always -r "$recipient" "$tmpfile"
+            if [[ $? -ne 0 ]]; then
+              faillist="$faillist\n$recipient"
+              echo "Key contained in $key is not valid for encryption"
+            fi
           done
 
-          if [[ -n $faillist ]]; then echo -e "The following keys are not valid:$faillist"; exit 1; fi
+          rm $tmpkeys $tmpfile
 
-          rm $tmpkeys
+          if [[ -n $faillist ]]; then echo -e "\nThe following keys are not valid:$faillist"; exit 1; fi
